<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CrossbodyBagTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2022-09-19T23:22:36" hostname="BLADE-STEALTH-A" time="0.047">
  <properties/>
  <testcase name="TestToString" classname="CrossbodyBagTest" time="0.047">
    <failure message="org.junit.ComparisonFailure: expected:&lt;...e Crossbody Bag with[ 2 ]straps (0 / 4)&gt; but was:&lt;...e Crossbody Bag with[2]straps (0 / 4)&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: expected:&lt;...e Crossbody Bag with[ 2 ]straps (0 / 4)&gt; but was:&lt;...e Crossbody Bag with[2]straps (0 / 4)&gt;
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at CrossbodyBagTest.TestToString(CrossbodyBagTest.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
